
import "./globals.css";
import NavigationBar from "@/components/NavigationBar";
import Providers from "@/components/Providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <Providers>
        <NavigationBar />
        {children}
        </Providers>
      </body>

    </html>
  );
}
